---
services:
  gmsa:
    restart: unless-stopped
    build:
      context: .
    environment:
      - TZ=Australia/Melbourne

  test:
    build:
      context: .
      target: test
    volumes:
      - ./gmsa:/src/gmsa
      - ./tests:/src/test
    depends_on:
      - gmsa
